import Head from 'next/head';
import '@/styles/globals.css';
import type { AppProps } from 'next/app';

export default function App({
    Component,
    pageProps,
    router,
}: AppProps): JSX.Element {
    return (
        <>
            <Head>
                <title>Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
                <meta
                    property="og:url"
                    content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath}
                />
                <meta property="og:locale" content="ru_RU" />
            </Head>
            <Component {...pageProps} />
        </>
    );
}
